### ISSUE TITLE
Sync subfolders 

### ISSUE THREAD

**Issue by sxe** [davidolrik/sublime-rsync-ssh#12]
Hi, 
at first thx, finally a working sync plugin, i was waiting for this a long time. :)

Anyway, it would be nice if a single subfolder could be synced like this:

source:
/folder/a/b/

target:
/target/b/

I have multiple folders in my project but i don't want to sync each root folder, just subsets of the child folders.

Project settings example:

```
"folders":
[
    {
        "path": "/folder/a"
    }
]

"remotes":
        {
            "/folder/a/b":
            [
                {
                    "enabled": 1,
                    "remote_host": "localhost",
                    "remote_path": "/target/b",
                }
            ],
```

**Comment by sxe** [comment]
Hey, 
it's me again.
Any idea how to sync a specific folder to the target location?

I have to sync a structure like this:

```
a
  b
  c
d
  e
  f
```

Now i only want to sync the content of c and f to a target folder but i cannot figure out how to do that.

**Comment by davidolrik** [comment]
This isn't easily done with rsync in one command, as you can't change the structure on the target side.

To sync c and f you have to include a and d, but exclude the rest, like this:

```
"--filter clear",
"--filter include,_a",
"--filter include,_a/c**",
"--filter include,_d",
"--filter include,_d/f**",
"--filter exclude,_*"
```

This will give you the following on the in the target directory:

```
a/c
d/f
```

**Comment by sxe** [comment]
Hi davidolrik, 
yeah i already tried that but unfortunately that's not what i need.
I have to be able to sync into single folder. :/

I regulary have to sync a single folder (no matter where it is located in a tree)
 to my target directory.  Would be nice if you could add this kind of functionality.

A simple way to specify multiple directories that would be synced to a single or multiple taget systems would be awesome.

Greetings

**Comment by davidolrik** [comment]
I have just released [v1.4.0](https://github.com/davidolrik/sublime-rsync-ssh/releases/tag/v1.4.0) which adds subfolder sync support.
It should show up in [Package Control](https://packagecontrol.io/packages/Rsync%20SSH) shortly.

**Comment by asakasinsky** [comment]
Really? Im test it later!!!!!

**Comment by sxe** [comment]
I already did, works great. :)

Thx a lot David.

**Comment by asakasinsky** [comment]
Works great Thank you!
