### ISSUE TITLE
Can I remove some of default rsync params?

### ISSUE THREAD

**Issue by mkomigor** [davidolrik/sublime-rsync-ssh#21]
```python
rsync_command = [
            "rsync", "-v", "-zar",
            "-e", "ssh -q -T -p " + str(self.remote.get("remote_port", "22")) + " -o ConnectTimeout="+str(self.timeout)
        ]

**Comment by davidolrik** [comment]
What are you trying to accomplish?

**Comment by juliobranha** [comment]
Same here 
-p and ConnectTimeout give me errors, the command works fine otherwise

**Comment by davidolrik** [comment]
Can you paste the error here?

**Comment by davidolrik** [comment]
...also what version of ssh do you have?

**Comment by juliobranha** [comment]
Sure :)

ssh 6.2 local, 5.3 remote

rsync: link_stat "/Users/juliobrana/22" failed: No such file or directory (2)
rsync: link_stat "/Users/juliobrana/ConnectTimeout=10" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]

When I run the command in a terminal
rsync -v -zar -e ssh -q -T -p 22 -o ConnectTimeout=10 --dry-run --delete /Users/juliobrana/webs/ft_blogs/html/index.php julio.brana@whatever.remote:/var/tmp/Julio.Brana/blogs/html/index.php --exclude=.git* --exclude=.DS_Store

I don't get any error in the sublime console, seems everything is fine, but then the sync doesn't work. I removed all the options from the command and then it works fine in Sublime.

Maybe I am doing something wrong, I don't know much about rsync or ssh, just a developer :)

**Comment by davidolrik** [comment]
@juliobranha: I see your error, by default ` --dry-run ` is added so you can test the command before running it live.

If you remove ` --dry-run ` sync should work as expected ;-)

**Comment by juliobranha** [comment]
You were right. Works like a charm now :)

Thanks!

**Comment by davidolrik** [comment]
I'm going to close the issue now, due to no response from the original poster.
