### ISSUE TITLE
ssh option of rsync command should be quoted

### ISSUE THREAD

**Issue by haje01** [davidolrik/sublime-rsync-ssh#24]
I have trouble with following rsync command, which was generated by your plugin:

    rsync -v -zar -e ssh -q -T -p 22 -o ConnectTimeout=10 --dry-run --delete /Users/~/index.html ubuntu@~/index.html --exclude=.DS_Store --exclude=.ropeproject --exclude=.*.swp --exclude=.git

which should be fixed like this:

    rsync -v -zar -e "ssh -q -T -p 22 -o ConnectTimeout=10" --dry-run --delete /Users/~/index.html ubuntu@~/index.html --exclude=.DS_Store --exclude=.ropeproject --exclude=.*.swp --exclude=.git

Please refer following SO:

http://stackoverflow.com/questions/18270512/rsync-and-ssh-on-android-no-such-file-or-directory

**Comment by davidolrik** [comment]
It is already quoted, just not in the the output in the console. (When calling `subprocess.check_output` in list context each element is passed as one string, and all the arguments to `-e` is concatenated into one string.)

What is your actual problem? - Do you have a error message to a stack trace?

Also, your local path is broken, and your remote is missing a hostname.

**Comment by haje01** [comment]
I am sorry to make you confuse with my local path and hostname. It was omitted on purpose.
I misunderstood your code, and fault was in my settings.
I feel very very sorry..

Closing the issue.

**Comment by davidolrik** [comment]
No worries =)
