### ISSUE TITLE
Missing newline when host is disabled

### ISSUE THREAD

**Issue by hultberg** [davidolrik/sublime-rsync-ssh#26]
Hello, this is no major issue but rather a minor tweak (I hope).
I noticed when all my hosts are disabled that the message being sent to the console is missing a newline:
![screenshot - 150715 - 15 07 56](https://cloud.githubusercontent.com/assets/1257913/8699125/6bd0c188-2b03-11e5-9d7d-05a6ad41a29e.png)

**Comment by davidolrik** [comment]
Strange, I can't reproduce it.

What platform and what version of the plugin are you using?

**Comment by hultberg** [comment]
I'm using debian jessie (uname: 3.16.0-4-amd64) with version 1.5.0 of the plugin.

**Comment by davidolrik** [comment]
Which version of Sublime Text 3?

**Comment by hultberg** [comment]
Using build 3083

**Comment by davidolrik** [comment]
I'v tried 3090 on a Mac and 3083 64-bit on Ubuntu, and I can't reproduce it.

I suspect it is a bug in Sublime it self, as all console messages are printed with the same function.
It is quite weird though....

**Comment by hultberg** [comment]
On my debian desktop with testing, sublime 3083 and rsync ssh 1.5.0 I do not have this issue.

**Comment by davidolrik** [comment]
Guess there is not much I can do about it then...
