### ISSUE TITLE
Installation ?

### ISSUE THREAD

**Issue by rudzboy** [davidolrik/sublime-rsync-ssh#28]
Using Package Control....
what's the plugin name, can't find it.

Thx ;)

**Comment by davidolrik** [comment]
It's [rsync-ssh](https://packagecontrol.io/packages/Rsync%20SSH).

**Comment by rudzboy** [comment]
I'm sorry but autocompletion don't find it.
I'm using Sublime Text 2. Is your plugin usable with the 3rd version ? If yes, it's not clearly visible when reading manual.

Thx

**Comment by davidolrik** [comment]
It's for Sublime Text 3 only.

If you look at the top of the Package Control page for [rsync-ssh](https://packagecontrol.io/packages/Rsync%20SSH), there at some tags that show which version and platforms that are supported.

**Comment by rudzboy** [comment]
OK, thanks for your answer.
Still learning Sublime Text as you can see ;) Awesome BTW

**Comment by davidolrik** [comment]
No worries =)
