### ISSUE TITLE
Package doesn't show up in Package Control

### ISSUE THREAD

**Issue by cwharland** [davidolrik/sublime-rsync-ssh#29]
Would love to install via package control in sublime text 3 but searching both `rsync-ssh` and `Rsync SSH` doesn't yield any results.  Only package that does show up is a year old or so rsync package by a different author.

**Comment by davidolrik** [comment]
That's strange, as others have been able to install it via package control, at least according to the [graph](https://packagecontrol.io/packages/Rsync%20SSH).

Which platform are you on?

**Comment by rchl** [comment]
It doesn't show up on Windows, but it's expected as it's not supported there (at least until #31) :)

**Comment by davidolrik** [comment]
Waiting for https://github.com/wbond/package_control_channel/pull/4795 to be merged.

**Comment by davidolrik** [comment]
Windows support is now live on [packagecontrol.io](https://packagecontrol.io/packages/Rsync%20SSH)!
