### ISSUE TITLE
Does not properly handle spaces in folder names or file names

### ISSUE THREAD

**Issue by brianbruggeman** [davidolrik/sublime-rsync-ssh#32]
I haven't spent any time looking into the code, but I have noticed that when I have spaces in my folder names, the content is sent to a container folder up in the hierarchy tree and not to the specific file.

So for example, if we had:
"ALongPath/With/Some Path/To a File.txt"

The contents of "To a File.txt" would show up on the remote system as:
"ALongPath/With/Some"

**Comment by davidolrik** [comment]
Which platform are you on?

**Comment by brianbruggeman** [comment]
I'm on a Mac connecting to a Ubuntu box

**Comment by brianbruggeman** [comment]
Thanks David!

**Comment by davidolrik** [comment]
No problem, a new release will be pushed out shortly =)
