### ISSUE TITLE
How to use rsync in Windows ?

### ISSUE THREAD

**Issue by WinmanSoftwarePvtLtd** [davidolrik/sublime-rsync-ssh#39]
Hello, 
Is it possible to use rsync in Windows ? 
I read Dropbox is using rsync for synchronization of files. How to sync folders if source is Windows OS and destination is Linux server ?
or if both source and destinations are Windows OS ?
Please help me.

**Comment by rchl** [comment]
I use this plugin on Windows together with the rsync included in the https://www.cygwin.com/ .
I use it for syncing between Windows and Linux.

If you would want to sync between Windows machines then I guess one would have to run SSH server. I don't know much about that though.
