### ISSUE TITLE
sublime-rsync-ssh feature suggestion to allow sublime-project configuration to define ssh private key path

### ISSUE THREAD

**Issue by brucekirkpatrick** [davidolrik/sublime-rsync-ssh#50]
Hello, I found your project to be perfect for my goal of using rsync and sublime text instead of ftp.

I'm trying to use this plugin on windows to connect to linux and I couldn't figure out a configuration that works for key authentication using cygwin.  I did get it working without a password being required, so I know there wasn't anything failing except ssh authentication.   I assume this is easier on a mac or linux machine where ssh is native.  It seems like a pain to have to deal with cygwin since ssh-agent doesn't seem to work or I lack the knowledge after trying a few things.   I looked into modifying your plugin to add the ssh key path argument to the rsync / ssh command and found that to be an easier solution.

I suggest adding a feature to the open source project to make it easier for others to set their ssh private key path in the sublime-project file like this:

in sublime-project settings:
after "remote_port": 2222,

add:
"ssh_key_path":"/absolute/path/to/private_key",

and then in rsync_ssh.py after this line:
        if self.destination.get("remote_port"):
            ssh_command.extend(["-p", str(self.destination.get("remote_port"))])
add this:
        if self.destination.get("ssh_key_path"):
            ssh_command.extend(["-i", str(self.destination.get("ssh_key_path"))])

This worked for me, and this lets me use a simple setup for cygwin on windows.

Or if you know a better way, perhaps provide some docs for it since authentication is the one thing lacking in the current readme.

Thanks for making this plugin and good job with the docs and feature set so far!

**Comment by Rob-Schneider** [comment]
Yes, working.
but why it does not added in project yet?

**Comment by ctheune** [comment]
This works now by using the `ssh_args` option. 

@davidolrik this can be closed, I think
