### ISSUE TITLE
Custom SSH parameters

### ISSUE THREAD

**Issue by ctheune** [davidolrik/sublime-rsync-ssh#57]
I am working in an environment where I rely on different (auto-generated) SSH config files

I can add the custom SSH parameters via 

``
            "options": [
            	"--rsh='ssh -F /Path/To/My/ssh_config_dev'",
            ],
``

However, this causes the check command to fail:

```
[rsync-ssh] container[fc.directory]:        ssh -q -T -o ConnectTimeout=10 ctheune@container LANG=C which rsync
```

I think I can work around this for a while by using a custom SSH command, but that's hacky. I'm happy to contribute a patch with an option for custom SSH parameters (and then make that create the `--rsh` option as well.

**Comment by davidolrik** [comment]
Sounds like a good idea - patches welcome =)

**Comment by ctheune** [comment]
Alright. I have switched from my personal old rsync plugin and added the stuff I noticed in #58 ... 

In addition to that, would you be willing to switch to black and add pre-commit hooks and maybe a bit of unit testing?

I'd be happy to contribute all of those.

**Comment by davidolrik** [comment]
Fixed in #58

**Comment by davidolrik** [comment]
Regarding black and testing - that would be nice 😀

**Comment by ctheune** [comment]
Also, I think I broke it in the PR, I just noticed that single-file syncs are now missing the correct target path ...

**Comment by ctheune** [comment]
So much for tests :)
